# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__, np.show_config())

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.43.34808",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.2",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.43.34808",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.29",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-9tmma_o0/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib directo

d:\mukul\Desktop\Unimelb\numpy-100\.venv\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
a = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [10]:
# a.size is the number of elements in the array
# a.itemsize is the size in bytes of each element in the array
print(a.size*a.itemsize)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
! python -c "import numpy as np; np.info(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
a = np.zeros(10)
a[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
a = np.arange(10,50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
a = np.arange(10)
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
a = [1,2,0,0,4,0]
np.nonzero(a)[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
np.random.rand(3,3,3)

array([[[0.85488175, 0.8220561 , 0.48592064],
        [0.02213549, 0.44194212, 0.33616879],
        [0.20397064, 0.39999989, 0.55275383]],

       [[0.29408027, 0.19348262, 0.66893451],
        [0.39472677, 0.80306111, 0.07054702],
        [0.5679078 , 0.45557406, 0.74850259]],

       [[0.27581746, 0.41797454, 0.36992066],
        [0.36250004, 0.86883191, 0.97808356],
        [0.40251787, 0.30038702, 0.37778018]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
a = np.random.rand(10,10)
print(a.min(), a.max())

0.013440161634570402 0.9878817061999278


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
a = np.random.random(30)
print(a.mean())

0.5438778052597526


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [30]:
z = np.zeros((4,4))
z = np.pad(z, pad_width=1, mode='constant', constant_values=1)
z

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [31]:
np.pad(z, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan                  # np.nan
np.nan == np.nan            # False
np.inf > np.nan             # False 
np.nan - np.nan             # np.nan 
np.nan in set([np.nan])     # True  : in set
0.3 == 3 * 0.1              # False : floating point errors
```

In [33]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [35]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [40]:
a = np.zeros((8,8), dtype=int)
a[1::2, ::2]=1
a[::2, 1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [41]:
z = np.zeros((6,7,8))
# 100th element mapped to (x, y, z) coordinates -
print(np.unravel_index(99, z.shape))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [43]:
z = np.tile(np.array([[0,1],[1,0]]), (4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [47]:
z = np.random.random((5,5))
# normaise
z = (z - np.mean(z)) / np.std(z)
print(z)

[[ 1.09472312 -1.48941432 -1.3167516   0.69436667  0.68574812]
 [ 1.84834262 -0.03043658  0.16278316  0.14486428 -0.24190938]
 [ 1.59878616 -0.29299268  1.81864446  1.1782978  -0.95886727]
 [ 0.64811934 -0.93079201 -0.84099274 -1.3184262  -1.46612583]
 [-0.92342553  0.012708    0.46577329 -0.36564304 -0.17737985]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [48]:
color = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte, 1),    
                 ("b", np.ubyte, 1),
                 ("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [51]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
c = a @ b
c.shape

(5, 2)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [54]:
a = np.arange(10)
a[(a>3) & (a<8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))    # adds up range(5) -> 10 and -1 -> 9
from numpy import *
print(sum(range(5),-1))    # now its np.sum  and now -1 is treated as axis so it does sum on last axis -> 10
```

In [ ]:
import numpy as np
print(sum(range(5), -1))  # built-in sum
print(np.sum(range(5), -1))  # numpy sum with axis

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

```python
Z**Z                   # element wise exponentiation
2 << Z >> 2            # bitwise shift operators
Z <- Z                 # z < (-z) element wise comparison 
1j*Z                   # 1j imaginary * z 
Z/1/1                  # divison chain 
Z<Z>Z                  # ambigious **illegal**
```

In [63]:
z = np.arange(1, 11, dtype=np.int16)
print(z**z)                   # element wise exponentiation
print(2 << z >> 2)            # bitwise shift operators
print(z < -z)                 # z < (-z) element wise comparison
print(1j * z)                 # 1j imaginary * z
print(z / 1 / 1)              # division chain


[     1      4     27    256   3125 -18880 -28425      0 -28343  -7168]
[  1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False]
[0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j 0. +9.j
 0.+10.j]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)                           # divide by zero warning
np.array(0) // np.array(0)                          # divide by zero floor divide
np.array([np.nan]).astype(int).astype(float)        # error casting np.nan to int 
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [83]:
z = np.random.uniform(-1,1,5)*10
y = np.copysign(np.ceil(np.abs(z)), z)
print(z, y)

[ 6.18708419  7.27391596 -0.83479378  0.58926523 -0.04869601] [ 7.  8. -1.  1. -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [93]:
a = np.random.randint(0,10,(10,1))
b = np.random.randint(0,10,(10,1))
# common values
common_values = np.intersect1d(a, b) # sorts the values may be unnecessary
print(common_values)

# method 2 using mask, not unique values
mask = np.isin(a, b)
common_values_mask = a[mask]
print(common_values_mask)

[1 3 6 9]
[6 1 3 9 9 1 1]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [94]:
# ignore 
default = np.seterr(all='ignore')  # ignore all numpy warnings
# restore to default
np.seterr(**default)  # restore to default warnings

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

```python
np.sqrt(-1)  # doesnt support imaginary number, will raise warning
```
```python
np.emath.sqrt(-1)  # handles imaginary number
```

returns false

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [97]:
today_date = np.datetime64('today', 'D')
yesterday_date = today_date - np.timedelta64(1, 'D')
tomorrow_date = today_date + np.timedelta64(1, 'D')
print(today_date, yesterday_date, tomorrow_date)

2025-07-21 2025-07-20 2025-07-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [98]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [100]:
A = np.random.random((3,3))
B = np.random.random((3,3))
# B = A+B
np.add(A,B,out=B)
# A = A/2
np.divide(A,2,out=A)
# A = -A
np.negative(A,out=A)
# A = A*B
np.multiply(A,B,out=A)

array([[-0.39553782, -0.3323637 , -0.18729776],
       [-0.43812603, -0.02131296, -0.42939437],
       [-0.19616611, -0.83488692, -0.04872797]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [102]:
Z = np.random.uniform(0,10,5)
print(np.floor(Z))
print(Z // 1)
print(Z.astype(int))
print(np.trunc(Z))

[0. 6. 2. 3. 5.]
[0. 6. 2. 3. 5.]
[0 6 2 3 5]
[0. 6. 2. 3. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [105]:
np.tile(np.arange(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [107]:
def gen():
    yield from np.arange(10) 
np.fromiter(gen(), dtype=int, count=-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [112]:
a = np.linspace(0, 1, num=10, endpoint=False)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [115]:
a = np.random.random(10)
a.sort()
print(a)

[0.03255752 0.10906304 0.21653065 0.30196603 0.50033718 0.5303367
 0.81673889 0.83228644 0.83605798 0.99368866]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [117]:
np.add.reduce(np.ones(5, dtype=int))  # sum of ones

np.int64(5)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [119]:
a = np.random.random(10)
b = np.random.random(10)

print(np.allclose(a, b))  # check if two arrays are element-wise equal within a tolerance
print(np.array_equal(a, b))  # check if two arrays are exactly equal


False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [122]:
a = np.ones(10, dtype=int)
a.flags.writeable = False  # make the array read-only
print(a.flags.writeable)  # check if the array is writable
a[1] = 2  # this will raise an error since the array is read-only   

False


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [124]:
cartesian_cords = np.random.rand(10,2)
# cartesian to polar conversion
polar_cords = np.zeros(cartesian_cords.shape)
polar_cords[:, 0] = np.sqrt(cartesian_cords[:, 0]**2 + cartesian_cords[:, 1]**2)  # radius
polar_cords[:, 1] = np.arctan2(cartesian_cords[:, 1], cartesian_cords[:, 0])  # angle

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [128]:
a = np.random.rand(10)
a[a.argmax()] = 0.0  # set max value to zero
a

array([0.29848266, 0.41436064, 0.1041403 , 0.93416467, 0.        ,
       0.40387434, 0.69993171, 0.51042303, 0.40583321, 0.64424768])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [143]:
n = 5
xy = np.zeros((n,n), [('x',float),('y',float)])
xy['x'], xy['y'] = np.meshgrid(np.linspace(0, 1, n), np.linspace(0, 1, n))
print(xy)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix $C(C_{ij} =1/(x_i - y_j))$ (★★☆)

In [156]:
X = np.random.random(size=(5,))
Y = np.random.random(size=(5,))
# cauchy matrix
C = 1.0 / np.subtract.outer(X, Y)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [168]:
for dtype in [np.int8, np.int32, np.int64]:
   print(f" dtype: {dtype}, min: {np.iinfo(dtype).min}, max: {np.iinfo(dtype).max}")
for dtype in [np.float32, np.float64]:
   print(f" dtype: {dtype}, min: {np.finfo(dtype).min}, max: {np.finfo(dtype).max}, eps: {np.finfo(dtype).eps}")


 dtype: <class 'numpy.int8'>, min: -128, max: 127
 dtype: <class 'numpy.int32'>, min: -2147483648, max: 2147483647
 dtype: <class 'numpy.int64'>, min: -9223372036854775808, max: 9223372036854775807
 dtype: <class 'numpy.float32'>, min: -3.4028234663852886e+38, max: 3.4028234663852886e+38, eps: 1.1920928955078125e-07
 dtype: <class 'numpy.float64'>, min: -1.7976931348623157e+308, max: 1.7976931348623157e+308, eps: 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [170]:
np.set_printoptions(threshold=float("inf"))
print(np.random.rand(4))

[0.81728572 0.37253432 0.94299135 0.77414221]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [174]:
a = np.random.rand(10)*10
print(a)
# lets say finding the closest value to mean
idx = np.abs(a - a.mean()).argmin()
print(f"Index of closest value to mean {a.mean()}: Index: {idx}, Value: {a[idx]}")

[1.50283137 1.31802349 0.69064262 4.92605031 9.55590659 0.2137018
 1.52764748 4.12968314 9.30992252 5.03930119]
Index of closest value to mean 3.8213710512421373: Index: 7, Value: 4.129683140887964


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)